"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-&^p&$u7w_a(^8n=lw4)yq_unedyoghyv#s4oe_hwrpg7lu%crd"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost' , '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Hiding technology
    "django_hide",

    # text editor
    "django_quill",

    # config blog
    "blog.apps.BlogConfig",

    # config user
    "user.apps.UserConfig",

    # ReCaptcha 
    "captcha",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # Hiding technology
    "django_hide.middleware.CSRFHIDEMiddleware",

    # whitenoise : Radically simplified static file serving for Python web apps 
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            # templates path
            os.path.join(BASE_DIR, 'templates'),
            # media src path -- blog
            os.path.join(BASE_DIR, 'blog/media'),
            # media src path -- user
            os.path.join(BASE_DIR, 'user/media'),
            
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "tedora",
        "USER": "behshad",
        "PASSWORD": "#Mr-RahmanPour-2004-9814*45*83",
        "HOST": "localhost",
        "PORT":'',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", },
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator", },
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator", },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# URL to use when referring to static files located in STATIC_ROOT.
STATIC_URL = "static/"

# managing stored files
MEDIA_URL = ''  # or MEDIA_URL = '/upload/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

# Storage location for uploaded files
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/upload/')

# The absolute path to the directory where collectstatic will collect static files for deployment.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ًReCaptcha Key
RECAPTCHA_PUBLIC_KEY = '6Le2-7whAAAAAHy0hcBqYNFxs9U03BGi8kwCT2tq'
RECAPTCHA_PRIVATE_KEY = '6Le2-7whAAAAABw65F4uXJ3KVqOnvA_YQamvRz4c'
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']



# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
