# Generated by Django 4.1 on 2022-08-12 07:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateField(auto_now=True)),
                ("label", models.CharField(max_length=255, unique=True)),
            ],
            options={"ordering": ["-created"],},
        ),
        migrations.CreateModel(
            name="Essays",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateField(auto_now=True)),
                ("title", models.CharField(max_length=250, unique=True)),
                ("description", models.TextField()),
                (
                    "source_link",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("demo_link", models.CharField(blank=True, max_length=2000, null=True)),
                ("total_vote", models.IntegerField(default=0)),
                (
                    "positive_vote",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                ("tag", models.ManyToManyField(related_name="+", to="blog.tags")),
            ],
            options={"ordering": ["-created"],},
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateField(auto_now=True)),
                (
                    "comment",
                    models.CharField(
                        choices=[
                            (
                                "I read essay",
                                "I read this essay and realized many concepts .",
                            ),
                            (
                                "I have not finished this essay",
                                "I have not been able to read this article to the end and understand its concepts .",
                            ),
                            (
                                "I not read essay",
                                "I am not interested in reading this article .",
                            ),
                        ],
                        default="I read essay",
                        max_length=255,
                    ),
                ),
                (
                    "essay",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.essays"
                    ),
                ),
            ],
            options={"ordering": ["-created"],},
        ),
    ]
