# Generated by Django 4.1.1 on 2022-09-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment_body_comment_owner_alter_comment_essay_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.CharField(
                choices=[
                    ("I read essay", "I read this essay and realized many concepts ."),
                    (
                        "I have not finished this essay",
                        "I have not been able to read this article to the end and understand its concepts .",
                    ),
                    (
                        "I not read essay",
                        "I am not interested in reading this article .",
                    ),
                ],
                default="I read essay",
                max_length=300,
            ),
        ),
    ]
