# Generated by Django 4.1.1 on 2022-09-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_body_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, max_length=70, unique=True),
        ),
    ]
