# Generated by Django 4.1 on 2022-08-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_essays_upload_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="essays",
            name="upload_image",
            field=models.ImageField(
                default="static/img/surface.jpg", upload_to="upload/"
            ),
        ),
    ]
