# Generated by Django 4.1.1 on 2022-09-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_essay_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=70, unique=True),
        ),
    ]
