# Generated by Django 4.1.1 on 2022-09-06 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "avatar",
                    models.ImageField(
                        default="/static/avatar/4.png", upload_to="profile/"
                    ),
                ),
                ("full_name", models.CharField(max_length=25, unique=True)),
                ("username", models.CharField(max_length=25, unique=True)),
                ("email", models.EmailField(max_length=30, unique=True)),
                ("specialty", models.CharField(max_length=50)),
                ("bio", models.TextField(max_length=150)),
                ("github", models.CharField(blank=True, max_length=25, null=True)),
                ("twitter", models.CharField(blank=True, max_length=25, null=True)),
                ("linkedin", models.CharField(blank=True, max_length=25, null=True)),
                ("instagram", models.CharField(blank=True, max_length=25, null=True)),
                ("telegram", models.CharField(blank=True, max_length=25, null=True)),
                ("website", models.CharField(blank=True, max_length=25, null=True)),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=25)),
                (
                    "description",
                    models.TextField(blank=True, max_length=135, null=True),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.profile"
                    ),
                ),
            ],
        ),
    ]
