# Generated by Django 4.1 on 2022-08-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile", name="bio", field=models.TextField(max_length=140),
        ),
    ]
