# Generated by Django 4.1.1 on 2022-09-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_avatar_alter_skill_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/static/avatar/4.png', upload_to='profile/'),
        ),
    ]
