# Generated by Django 4.1 on 2022-08-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="description",
            field=models.TextField(blank=True, max_length=135, null=True),
        ),
        migrations.AlterField(
            model_name="skill", name="label", field=models.CharField(max_length=25),
        ),
    ]
